import "./globals.css";

export const metadata = {
  title: "Portfolio Gonzalo Mancebo - Full Stack Developer & Web Developer",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Esta línea asegura que usemos el favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body>{children}</body>
    </html>
  );
}
